version: "3.0"

services:
  rest-interface:
    build: ./
    # gunicorn project_finance.wsgi:application -w 4 --bind 0.0.0.0:8000 
    command: gunicorn -w 4 --bind 0.0.0.0:8000 "recht:create_app()"
    expose:
      - 8000
    container_name: steuerrecht
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    container_name: reverse-proxy
    labels:
      kompose.service.type: LoadBalancer
