FROM python:3.11.0-alpine

RUN pip3 install --upgrade pip
# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip3 install -r requirements.txt
EXPOSE 8000
# copy every content from the local file to the image
COPY . /app
 
ENV FLASK_APP=recht
ENV FLASK_ENV=development
# configure the container to run in an executed manner
CMD [ "gunicorn", "-w 4", "--bind=0.0.0.0:8000", "recht:create_app()" ]